services:
  #our PostgreSQl database
  db:
    #using the latest psotgreSQL image
    image: postgres:latest
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      TZ: Asia/Kolkata
      POSTGRES_PASSWORD: changemeinprod!

  #Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080